version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"

  payment-service:
    build: ./payment-service
    ports:
      - "3003:3003"
